owner: cnbwebmaster
repo: CNB-Status-Page

sites:
  - name: Career Now Brands Website
    url: https://careernowbrands.com
    maxResponseTime: 10000
  - name: Monday.com
    url: https://monday.com
    maxResponseTime: 10000
  - name: Braze
    url: https://www.braze.com
    maxResponseTime: 10000
  - name: Jira (Atlassian)
    url: https://jira.atlassian.com
    maxResponseTime: 10000
  - name: Confluence (Atlassian)
    url: https://confluence.atlassian.com
    maxResponseTime: 10000
  - name: Tableau Cloud (SSO)
    url: https://sso.online.tableau.com/
    maxResponseTime: 10000
  - name: HubSpot
    url: https://app.hubspot.com
    maxResponseTime: 10000
  - name: Slack
    url: https://slack.com
    maxResponseTime: 10000
  - name: Five9
    url: https://login.five9.com/
    maxResponseTime: 10000
  - name: Cloudflare
    url: 1.1.1.1
    port: 53
    check: tcp-ping
  - name: Google (Connectivity Check)
    url: https://www.google.com
    maxResponseTime: 10000

status-website:
  baseUrl: /CNB-Status-Page
  logoUrl: /CNB-Status-Page/assets/images.png
  name: Career Now Brands Status
  introTitle: "System Status"
  introMessage: "Live uptime and incident reporting for Career Now Brands internal and customer-facing systems."
  navbar:
    - title: Status
      href: /
  customCSS: |
    :root {
      --body-background-color: linear-gradient(180deg, #8b1120 0%, #3a070c 45%, #000000 100%) !important;
      --body-text-color: #ffffff !important;
      --card-background-color: rgba(0, 0, 0, 0.55) !important;
    }
    html, body {
      background: var(--body-background-color) !important;
      color: var(--body-text-color) !important;
    }
    main section {
      display: grid !important;
      grid-template-columns: repeat(auto-fit, minmax(360px, 1fr)) !important;
      gap: 18px !important;
    }
    .container {
      max-width: 1900px !important;
      width: calc(100vw - 80px) !important;
    }
