owner: cnbwebmaster
repo: CNB-Status-Page

sites:
  - name: Career Now Brands Website
    url: https://careernowbrands.com
    maxResponseTime: 10000

  # Core tools (monitor the product you use, not just their public status page)
  - name: Monday.com
    url: https://monday.com
    maxResponseTime: 10000

  - name: Braze
    url: https://www.braze.com
    maxResponseTime: 10000

  - name: Jira (Atlassian)
    url: https://jira.atlassian.com
    maxResponseTime: 10000

  - name: Confluence (Atlassian)
    url: https://confluence.atlassian.com
    maxResponseTime: 10000

  - name: Tableau Cloud (SSO)
    url: https://sso.online.tableau.com/
    maxResponseTime: 10000

  - name: HubSpot
    url: https://app.hubspot.com
    maxResponseTime: 10000

  - name: Slack
    url: https://slack.com
    maxResponseTime: 10000

  - name: Cloudflare
    url: https://dash.cloudflare.com
    maxResponseTime: 10000

  # Optional: keep one “external internet sanity check”
  - name: Google (Connectivity Check)
    url: https://www.google.com
    maxResponseTime: 10000

status-website:
  baseUrl: /CNB-Status-Page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Career Now Brands Status
  introTitle: "System Status"
  introMessage: "Live uptime and incident reporting for Career Now Brands internal and customer-facing systems."
  navbar:
    - title: Status
      href: /
    - title: GitHub Repository
      href: https://github.com/$OWNER/$REPO
