owner: cnbwebmaster
repo: CNB-Status-Page

sites:
  - name: Career Now Brands Website
    url: https://careernowbrands.com
    maxResponseTime: 10000
  - name: Monday.com
    url: https://monday.com
    maxResponseTime: 10000
  - name: Braze
    url: https://www.braze.com
    maxResponseTime: 10000
  - name: Jira (Atlassian)
    url: https://jira.atlassian.com
    maxResponseTime: 10000
  - name: Confluence (Atlassian)
    url: https://confluence.atlassian.com
    maxResponseTime: 10000
  - name: Tableau Cloud (SSO)
    url: https://sso.online.tableau.com/
    maxResponseTime: 10000
  - name: HubSpot
    url: https://app.hubspot.com
    maxResponseTime: 10000
  - name: Slack
    url: https://slack.com
    maxResponseTime: 10000
  - name: Five9
    url: https://login.five9.com/
    maxResponseTime: 10000
  - name: Cloudflare
    url: 1.1.1.1
    port: 53
    check: tcp-ping
  - name: Google (Connectivity Check)
    url: https://www.google.com
    maxResponseTime: 10000

status-website:
  baseUrl: /CNB-Status-Page
  logoUrl: /CNB-Status-Page/assets/images.png
  name: Career Now Brands Status
  customHeader: '<link rel="stylesheet" href="assets/custom.css">'
